services:
  backend-ubuntu:
    build: .
    container_name: ubuntu_dev_env
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
      - /app/build
      - /app/.gradle
    env_file:
      - .env
    command: tail -f /dev/null

  mongo-shard-a:
    image: mongo:latest
    container_name: mongo_shard_a
    ports:
      - "27017:27017"
    volumes:
      - mongo_shard_a_data:/data/db

  mongo-shard-b:
    image: mongo:latest
    container_name: mongo_shard_b
    ports:
      - "27018:27017"
    volumes:
      - mongo_shard_b_data:/data/db

volumes:
  mongo_shard_a_data:
  mongo_shard_b_data:
