services:
  backend-ubuntu:
    build: .
    container_name: ubuntu_dev_env
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
      - /app/build
      - /app/.gradle
    env_file:
      - .env
    command: tail -f /dev/null
